"use client";
import Link from "next/link";
import { FormEvent, useEffect, useMemo, useState } from "react";
import { CheckCircle2, Eye, Search, ShieldCheck } from "lucide-react";
import { supabase } from "@/lib/supabase";

type Submission={id:string;title:string;slug:string;status:string;engine:string;short_description:string;full_description:string;build_verified:boolean;updated_at:string;developer_profiles?:{studio_name?:string;display_name?:string};game_builds?:Array<{verification_status:string;preview_url?:string;build_type:string;compression_mode:string;file_count:number;total_bytes:number}>;game_media?:Array<{role:string;public_url:string}>};
export function DeveloperReviewPortal(){
  const [rows,setRows]=useState<Submission[]>([]);const [role,setRole]=useState("");const [selected,setSelected]=useState<Submission|null>(null);const [query,setQuery]=useState("");const [status,setStatus]=useState("all");const [message,setMessage]=useState("Checking reviewer access…");
  async function load(){const session=(await supabase?.auth.getSession())?.data.session;if(!session)return setMessage("Sign in with an authorized reviewer account.");const response=await fetch("/api/admin/developer-submissions",{headers:{Authorization:`Bearer ${session.access_token}`}});const payload=await response.json().catch(()=>({})) as {submissions?:Submission[];role?:string;error?:string};if(!response.ok)return setMessage(payload.error||"Reviewer access is required.");setRows(payload.submissions||[]);setRole(payload.role||"");setMessage("");}
  useEffect(()=>{void load();},[]);
  const filtered=useMemo(()=>rows.filter(row=>(status==="all"||row.status===status)&&`${row.title} ${row.slug} ${row.developer_profiles?.studio_name||""}`.toLowerCase().includes(query.toLowerCase())),[query,rows,status]);
  async function decide(event:FormEvent<HTMLFormElement>){event.preventDefault();if(!selected)return;const session=(await supabase?.auth.getSession())?.data.session;if(!session)return;const body=Object.fromEntries(new FormData(event.currentTarget));const response=await fetch("/api/admin/developer-submissions",{method:"POST",headers:{"Content-Type":"application/json",Authorization:`Bearer ${session.access_token}`},body:JSON.stringify({...body,submissionId:selected.id,checklist:{load:body.load==="on",controls:body.controls==="on",responsive:body.responsive==="on",content:body.content==="on"}})});const payload=await response.json().catch(()=>({})) as {error?:string};setMessage(response.ok?"Review decision recorded.":payload.error||"Decision could not be recorded.");if(response.ok){setSelected(null);await load();}}
  return <main className="min-h-screen bg-[#0D1118] px-5 py-10 text-white sm:px-8"><div className="mx-auto max-w-[1440px]"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-[.22em] text-uniblex-blue">Admin · Developer Portal</p><h1 className="mt-2 font-heading text-3xl sm:text-5xl">Submission review queue</h1><p className="mt-3 text-uniblex-gray">Server-authorized reviewer workflow · role: {role||"checking"}</p></div><Link href="/admin" className="btn-secondary">Back to admin</Link></div>
  <div className="card mt-8 grid gap-3 p-4 md:grid-cols-[1fr_220px]"><label className="relative"><Search className="absolute left-3 top-3.5 text-uniblex-gray" size={18}/><input value={query} onChange={event=>setQuery(event.target.value)} placeholder="Search game or studio" className="min-h-12 w-full rounded-xl border border-white/10 bg-black/20 pl-10 pr-4 outline-none"/></label><select value={status} onChange={event=>setStatus(event.target.value)} className="admin-select rounded-xl border border-white/10 bg-black/20 px-4"><option value="all">All statuses</option>{["submitted","under_review","changes_requested","approved","rejected","published","unpublished"].map(item=><option key={item}>{item}</option>)}</select></div>
  {message?<p role="status" className="mt-5 rounded-xl border border-white/10 bg-white/5 p-4">{message}</p>:null}
  <section className="mt-5 overflow-hidden rounded-2xl border border-white/10 bg-black/20">{filtered.map(row=><article key={row.id} className="flex flex-col gap-4 border-b border-white/10 p-5 last:border-0 md:flex-row md:items-center"><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><h2 className="font-bold">{row.title}</h2><span className="rounded-full bg-white/5 px-2 py-1 text-xs uppercase text-uniblex-gray">{row.status}</span>{row.build_verified?<span className="rounded-full bg-emerald-400/10 px-2 py-1 text-xs text-emerald-300">BUILD VERIFIED</span>:null}</div><p className="mt-2 text-sm text-uniblex-gray">{row.developer_profiles?.studio_name||row.developer_profiles?.display_name||"Developer"} · {row.engine||"Engine not set"} · {new Date(row.updated_at).toLocaleString()}</p></div><button onClick={()=>setSelected(row)} className="btn-secondary !min-h-10 text-sm"><Eye size={16}/>Review</button></article>)}{!filtered.length?<div className="p-12 text-center text-uniblex-gray">No submissions match this queue.</div>:null}</section>
  {selected?<div className="fixed inset-0 z-50 overflow-y-auto bg-black/80 p-4"><form onSubmit={decide} className="card mx-auto my-8 max-w-4xl p-6 sm:p-8"><div className="flex justify-between gap-4"><div><p className="text-xs font-bold uppercase text-uniblex-blue">Reviewing</p><h2 className="mt-2 font-heading text-3xl">{selected.title}</h2><p className="mt-2 text-uniblex-gray">{selected.full_description}</p></div><button type="button" onClick={()=>setSelected(null)} className="text-uniblex-gray">Close</button></div><div className="mt-6 grid gap-4 md:grid-cols-2"><div className="rounded-xl border border-white/10 bg-black/20 p-5"><h3 className="font-bold">Build report</h3>{selected.game_builds?.map((build,index)=><div key={index} className="mt-3 text-sm text-uniblex-gray"><p>{build.verification_status} · {build.build_type} · {build.compression_mode}</p><p>{build.file_count} files · {Math.round(build.total_bytes/1024/1024)} MB</p>{build.preview_url?<a href={build.preview_url} target="_blank" rel="noreferrer" className="mt-3 inline-flex text-uniblex-blue">Open safe preview</a>:null}</div>)}</div><div className="rounded-xl border border-white/10 bg-black/20 p-5"><h3 className="font-bold">Review checklist</h3>{[["load","Loads without missing files"],["controls","Controls work as declared"],["responsive","Canvas and mobile layout pass"],["content","Content, IP, privacy and safety pass"]].map(([name,label])=><label key={name} className="mt-3 flex gap-3 text-sm"><input name={name} type="checkbox" className="accent-[#00B2FF]"/>{label}</label>)}</div></div><label className="mt-5 block text-sm font-bold">Developer-visible feedback<textarea name="developerFeedback" rows={4} className="mt-2 w-full rounded-xl border border-white/10 bg-black/20 p-4 outline-none focus:border-uniblex-blue"/></label><label className="mt-5 block text-sm font-bold">Private internal notes<textarea name="internalNotes" rows={4} className="mt-2 w-full rounded-xl border border-white/10 bg-black/20 p-4 outline-none focus:border-uniblex-purple"/></label><label className="mt-5 block text-sm font-bold">Decision<select name="decision" className="admin-select mt-2 min-h-12 w-full rounded-xl border border-white/10 bg-black/20 px-4"><option value="under_review">Start review</option><option value="changes_requested">Request changes</option><option value="approved">Approve</option><option value="rejected">Reject</option>{["owner","admin"].includes(role)?<><option value="published">Publish</option><option value="unpublished">Unpublish</option></>:null}</select></label><button className="btn-primary mt-6"><CheckCircle2 size={18}/>Confirm decision</button></form></div>:null}
  </div></main>;
}
