"use client";

import Link from "next/link";
import { ChangeEvent, FormEvent, useEffect, useMemo, useRef, useState } from "react";
import { Check, ChevronLeft, ChevronRight, FileArchive, ImagePlus, Loader2, RotateCcw, Send, ShieldCheck, UploadCloud, X } from "lucide-react";
import { supabase } from "@/lib/supabase";
import { uploadGameMediaFile, type GameMediaUploadProgress, type VerifiedGameMedia } from "@/lib/gameMediaUploadClient";
import { uploadDeveloperBuild, type DeveloperBuildProgress } from "@/lib/developerBuildUploadClient";
import type { GameMediaRole } from "@/lib/r2GameMedia";

const steps=["Game Details","Game Options","Media","WebGL Build","Review"] as const;
const engines=["HTML5","Unity 6","Unity 2023","Unity 2022","Godot","Construct","GameMaker","GDevelop","Other"];
type Category={id:string;name:string;slug:string};
type Draft={id?:string;draftKey:string;title:string;slug:string;shortDescription:string;description:string;categoryId:string;tags:string;engine:string;primaryLanguage:string;ageRating:string;videoUrl:string;desktop:boolean;mobile:boolean;keyboard:boolean;touch:boolean;gamepad:boolean;multiplayer:boolean;saveProgress:boolean;orientation:string;aspectRatio:string;loading:string;controls:string;sessionLength:string;difficulty:string;playerCount:string;contentAccepted:boolean;ipAccepted:boolean;media:VerifiedGameMedia[];build?:{operationId:string;previewUrl:string;fileCount:number;totalBytes:number;buildType:string;compressionMode:string}};
const fresh=():Draft=>({draftKey:crypto.randomUUID(),title:"",slug:"",shortDescription:"",description:"",categoryId:"",tags:"",engine:"HTML5",primaryLanguage:"English",ageRating:"Everyone",videoUrl:"",desktop:true,mobile:false,keyboard:true,touch:false,gamepad:false,multiplayer:false,saveProgress:false,orientation:"landscape",aspectRatio:"16/9",loading:"",controls:"",sessionLength:"",difficulty:"",playerCount:"1",contentAccepted:false,ipAccepted:false,media:[]});

export function DeveloperWizard(){
  const [draft,setDraft]=useState<Draft|null>(null);const [categories,setCategories]=useState<Category[]>([]);const [step,setStep]=useState(0);const [busy,setBusy]=useState(false);const [message,setMessage]=useState("");const [mediaProgress,setMediaProgress]=useState<Record<string,GameMediaUploadProgress>>({});const [buildProgress,setBuildProgress]=useState<DeveloperBuildProgress|null>(null);const abortRef=useRef<AbortController|null>(null);
  useEffect(()=>{try{const raw=localStorage.getItem("uniblex-developer-draft");setDraft(raw?{...fresh(),...JSON.parse(raw),media:(JSON.parse(raw).media||[]).filter((item:VerifiedGameMedia)=>item.objectKey)}:fresh());}catch{setDraft(fresh());}},[]);
  useEffect(()=>{let active=true;void supabase?.from("categories").select("id,name,slug").eq("is_published",true).order("sort_order").then(({data})=>{if(active)setCategories((data||[]) as Category[]);});return()=>{active=false;};},[]);
  useEffect(()=>{if(draft)localStorage.setItem("uniblex-developer-draft",JSON.stringify(draft));},[draft]);
  const cover=draft?.media.find(item=>item.role==="cover");const thumbnail=draft?.media.find(item=>item.role==="thumbnail");const screenshots=draft?.media.filter(item=>item.role.startsWith("screenshot-"))||[];
  const errors=useMemo(()=>draft?validate(step,draft):[],[draft,step]);
  if(!draft)return <main className="grid min-h-[70vh] place-items-center"><Loader2 className="animate-spin text-uniblex-blue" /></main>;
  const activeDraft=draft;

  async function token(){const session=(await supabase?.auth.getSession())?.data.session;if(!session)throw new Error("Authentication expired. Sign in again.");return session.access_token;}
  async function save(status="draft"){
    const access=await token();const response=await fetch("/api/developer/submissions",{method:"POST",headers:{"Content-Type":"application/json",Authorization:`Bearer ${access}`},body:JSON.stringify({submission:{id:draft!.id,title:draft!.title,slug:draft!.slug,short_description:draft!.shortDescription,full_description:draft!.description,category_id:draft!.categoryId||null,tags:draft!.tags,engine:draft!.engine,primary_language:draft!.primaryLanguage,age_rating:draft!.ageRating,gameplay_video_url:draft!.videoUrl,status,content_declaration:{rights_confirmed:draft!.ipAccepted,policy_confirmed:draft!.contentAccepted},options:{desktop:draft!.desktop,mobile:draft!.mobile,keyboard:draft!.keyboard,touch:draft!.touch,gamepad:draft!.gamepad,multiplayer:draft!.multiplayer,save_progress:draft!.saveProgress,orientation:draft!.orientation,aspect_ratio:draft!.aspectRatio,loading_instructions:draft!.loading,controls:draft!.controls,session_length:draft!.sessionLength,difficulty:draft!.difficulty,player_count:draft!.playerCount}}})});const payload=await response.json().catch(()=>({})) as {submission?:{id:string};error?:string};if(!response.ok||!payload.submission)throw new Error(payload.error||"Draft could not be saved.");const next={...draft!,id:payload.submission.id};setDraft(next);return next;
  }
  async function next(){if(errors.length)return setMessage(errors[0]);setBusy(true);setMessage("");try{if(step===0&&!activeDraft.id)await save();setStep(current=>Math.min(4,current+1));}catch(error){setMessage(error instanceof Error?error.message:"Draft could not be saved.");}finally{setBusy(false);}}
  async function uploadMedia(event:ChangeEvent<HTMLInputElement>,role:GameMediaRole){const file=event.target.files?.[0];event.target.value="";if(!file)return;setBusy(true);setMessage("");const controller=new AbortController();abortRef.current=controller;try{const current=activeDraft.id?activeDraft:await save();const verified=await uploadGameMediaFile(file,current.id!,role,progress=>setMediaProgress(value=>({...value,[role]:progress})),controller.signal);setDraft(value=>value?{...value,media:[...value.media.filter(item=>item.role!==role),verified]}:value);}catch(error){setMessage(error instanceof Error?error.message:"Media upload failed.");}finally{setBusy(false);abortRef.current=null;}}
  async function uploadBuild(event:ChangeEvent<HTMLInputElement>){const file=event.target.files?.[0];event.target.value="";if(!file)return;setBusy(true);setMessage("");const controller=new AbortController();abortRef.current=controller;try{const current=activeDraft.id?activeDraft:await save();const result=await uploadDeveloperBuild(file,current.id!,setBuildProgress,controller.signal) as Record<string,any>;const manifest=result.manifest as {files:Array<unknown>;totalBytes:number;buildType:string;compressionMode:string};setDraft(value=>value?{...value,build:{operationId:String(result.operationId),previewUrl:String(result.previewUrl||""),fileCount:manifest.files.length,totalBytes:manifest.totalBytes,buildType:manifest.buildType,compressionMode:manifest.compressionMode}}:value);}catch(error){setMessage(error instanceof Error?error.message:"Build upload failed.");}finally{setBusy(false);abortRef.current=null;}}
  async function submit(event:FormEvent){event.preventDefault();const finalErrors=validate(4,activeDraft);if(finalErrors.length)return setMessage(finalErrors[0]);setBusy(true);try{await save("submitted");localStorage.removeItem("uniblex-developer-draft");setMessage("Submission received. Your review timeline is now available in My Games.");}catch(error){setMessage(error instanceof Error?error.message:"Submission could not be sent.");}finally{setBusy(false);}}
  function update<K extends keyof Draft>(key:K,value:Draft[K]){setDraft(current=>current?{...current,[key]:value}:current);}
  function discard(){if(!confirm("Discard this local draft? Verified uploaded files remain attached to the saved server draft."))return;localStorage.removeItem("uniblex-developer-draft");setDraft(fresh());setStep(0);setMessage("Local draft discarded.");}

  return <main className="mx-auto max-w-[1240px] px-5 py-10 sm:px-6 lg:px-8">
    <div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><p className="text-xs font-bold uppercase tracking-[.22em] text-uniblex-blue">Controlled submission</p><h1 className="mt-2 font-heading text-3xl text-white sm:text-5xl">Submit a browser game</h1></div><button onClick={discard} className="btn-secondary !min-h-10 text-sm"><RotateCcw size={16}/>Discard local draft</button></div>
    <ol className="mt-8 grid gap-2 sm:grid-cols-5">{steps.map((label,index)=><li key={label} className={`rounded-xl border p-3 text-xs font-bold ${index===step?"border-uniblex-blue bg-uniblex-blue/10 text-white":index<step?"border-emerald-400/25 bg-emerald-400/5 text-emerald-300":"border-white/10 text-uniblex-gray"}`}><span className="mr-2">{index<step?"✓":index+1}</span>{label}</li>)}</ol>
    <form onSubmit={submit} className="card mt-6 p-5 sm:p-8">
      {step===0?<Details draft={draft} update={update} categories={categories}/>:step===1?<Options draft={draft} update={update}/>:step===2?<Media draft={draft} cover={cover} thumbnail={thumbnail} screenshots={screenshots} progress={mediaProgress} onFile={uploadMedia}/>:step===3?<Build draft={draft} progress={buildProgress} onFile={uploadBuild}/>:<Review draft={draft}/>}
      {message?<p role="status" className="mt-6 rounded-xl border border-uniblex-blue/20 bg-uniblex-blue/10 p-4 text-sm text-white">{message}</p>:null}
      {errors.length?<ul className="mt-5 text-sm text-amber-200">{errors.map(error=><li key={error}>• {error}</li>)}</ul>:null}
      <div className="mt-8 flex flex-wrap items-center justify-between gap-3 border-t border-white/10 pt-6"><button type="button" disabled={step===0||busy} onClick={()=>setStep(value=>Math.max(0,value-1))} className="btn-secondary disabled:opacity-40"><ChevronLeft size={18}/>Back</button><div className="flex gap-3">{busy&&abortRef.current?<button type="button" onClick={()=>abortRef.current?.abort()} className="btn-secondary text-red-200"><X size={17}/>Cancel transfer</button>:null}{step<4?<button type="button" disabled={busy} onClick={()=>void next()} className="btn-primary disabled:opacity-50">{busy?<Loader2 className="animate-spin" size={18}/>:null}Continue <ChevronRight size={18}/></button>:<button disabled={busy} className="btn-primary disabled:opacity-50"><Send size={18}/>Submit for review</button>}</div></div>
    </form>
  </main>;
}

type Update=<K extends keyof Draft>(key:K,value:Draft[K])=>void;
function Details({draft,update,categories}:{draft:Draft;update:Update;categories:Category[]}){return <section><Heading title="Game details" text="Create the authoritative listing identity and content declaration."/><div className="mt-6 grid gap-4 md:grid-cols-2"><Field label="Game title" value={draft.title} onChange={value=>update("title",value)} required/><Field label="Unique slug" value={draft.slug} onChange={value=>update("slug",value.toLowerCase().replace(/[^a-z0-9-]+/g,"-"))} placeholder="neon-drift"/><label className="text-sm font-semibold text-white">Category<select value={draft.categoryId} onChange={event=>update("categoryId",event.target.value)} required className="admin-select mt-2 min-h-12 w-full rounded-xl border border-white/10 bg-black/20 px-4"><option value="">Choose a category</option>{categories.map(category=><option key={category.id} value={category.id}>{category.name}</option>)}</select></label><label className="text-sm font-semibold text-white">Engine<select value={draft.engine} onChange={event=>update("engine",event.target.value)} className="admin-select mt-2 min-h-12 w-full rounded-xl border border-white/10 bg-black/20 px-4">{engines.map(engine=><option key={engine}>{engine}</option>)}</select></label><Field label="Tags (comma separated)" value={draft.tags} onChange={value=>update("tags",value)}/><Field label="Primary language" value={draft.primaryLanguage} onChange={value=>update("primaryLanguage",value)}/><Field label="Age-rating declaration" value={draft.ageRating} onChange={value=>update("ageRating",value)}/><Field label="Gameplay video URL (optional)" value={draft.videoUrl} onChange={value=>update("videoUrl",value)} type="url"/><Area label="Short description" value={draft.shortDescription} onChange={value=>update("shortDescription",value)} maxLength={220}/><Area label="Full description" value={draft.description} onChange={value=>update("description",value)} maxLength={5000}/></div><div className="mt-5 grid gap-3"><CheckBox checked={draft.ipAccepted} onChange={value=>update("ipAccepted",value)} label="I confirm I am authorized to distribute the game, code, artwork, audio, fonts, and other assets."/><CheckBox checked={draft.contentAccepted} onChange={value=>update("contentAccepted",value)} label="I confirm the game follows Uniblex content, privacy, safety, and external-service requirements."/></div></section>;}
function Options({draft,update}:{draft:Draft;update:Update}){const toggles:[keyof Draft,string][]=[["desktop","Desktop support"],["mobile","Mobile support"],["keyboard","Keyboard controls"],["touch","Touch controls"],["gamepad","Gamepad"],["multiplayer","Multiplayer"],["saveProgress","Save progress"]];return <section><Heading title="Game options" text="Declare only capabilities that are present and tested in the submitted build."/><div className="mt-6 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{toggles.map(([key,label])=><CheckBox key={key} checked={Boolean(draft[key])} onChange={value=>update(key,value as never)} label={label}/>)}</div><div className="mt-6 grid gap-4 md:grid-cols-3"><Field label="Orientation" value={draft.orientation} onChange={value=>update("orientation",value)}/><Field label="Aspect ratio" value={draft.aspectRatio} onChange={value=>update("aspectRatio",value)}/><Field label="Player count" value={draft.playerCount} onChange={value=>update("playerCount",value)}/><Field label="Typical session length" value={draft.sessionLength} onChange={value=>update("sessionLength",value)}/><Field label="Difficulty" value={draft.difficulty} onChange={value=>update("difficulty",value)}/></div><div className="mt-4 grid gap-4 md:grid-cols-2"><Area label="Loading instructions" value={draft.loading} onChange={value=>update("loading",value)}/><Area label="Controls and instructions" value={draft.controls} onChange={value=>update("controls",value)}/></div></section>;}
function Media({cover,thumbnail,screenshots,progress,onFile}:{draft:Draft;cover?:VerifiedGameMedia;thumbnail?:VerifiedGameMedia;screenshots:VerifiedGameMedia[];progress:Record<string,GameMediaUploadProgress>;onFile:(event:ChangeEvent<HTMLInputElement>,role:GameMediaRole)=>void}){const slots:[GameMediaRole,string,VerifiedGameMedia|undefined][]=[["cover","Cover · 16:9, 1920×1080 recommended",cover],["thumbnail","Card thumbnail · 4:3, 1200×900 recommended",thumbnail],...Array.from({length:6},(_,index):[GameMediaRole,string,VerifiedGameMedia|undefined]=>[`screenshot-${index+1}` as GameMediaRole,`Screenshot ${index+1}`,screenshots.find(item=>item.role===`screenshot-${index+1}`)])];return <section><Heading title="Media and artwork" text="JPG, PNG, or WebP up to 15 MB. Files transfer directly to R2 and are verified by checksum."/><div className="mt-6 grid gap-4 md:grid-cols-2">{slots.map(([role,label,item])=><label key={role} className="rounded-xl border border-dashed border-white/15 bg-black/20 p-5 transition hover:border-uniblex-blue"><div className="flex items-start justify-between gap-4"><div><p className="font-bold text-white">{label}</p><p className="mt-1 text-xs text-uniblex-gray">{item?`${item.name} · verified`:"Choose original, accurate artwork"}</p></div>{item?<Check className="text-emerald-300"/>:<ImagePlus className="text-uniblex-blue"/>}</div>{progress[role]?<Progress label={progress[role].phase} value={progress[role].percentage}/>:null}<input type="file" accept="image/jpeg,image/png,image/webp" className="sr-only" onChange={event=>void onFile(event,role)}/></label>)}</div></section>;}
function Build({draft,progress,onFile}:{draft:Draft;progress:DeveloperBuildProgress|null;onFile:(event:ChangeEvent<HTMLInputElement>)=>void}){return <section><Heading title="WebGL build" text="ZIP extraction, path checks, engine detection, and checksums run in your browser. Only individual verified files go directly to R2."/><label className="mt-6 grid min-h-64 cursor-pointer place-items-center rounded-2xl border border-dashed border-white/15 bg-black/20 p-8 text-center hover:border-uniblex-blue"><div>{draft.build?<ShieldCheck className="mx-auto text-emerald-300" size={42}/>:<FileArchive className="mx-auto text-uniblex-blue" size={42}/>}<h3 className="mt-4 font-heading text-xl text-white">{draft.build?"Build verified":"Choose WebGL ZIP"}</h3><p className="mt-2 text-sm text-uniblex-gray">{draft.build?`${draft.build.buildType} · ${draft.build.compressionMode} · ${draft.build.fileCount} files`:"Unity and HTML5 builds up to the configured project limit"}</p>{progress?<Progress label={`${progress.phase}${progress.currentFile?` · ${progress.currentFile}`:""}`} value={progress.percentage}/>:null}</div><input type="file" accept=".zip,application/zip" className="sr-only" onChange={event=>void onFile(event)}/></label></section>;}
function Review({draft}:{draft:Draft}){return <section><Heading title="Review and submit" text="This snapshot becomes the auditable release reviewed by Uniblex."/><div className="mt-6 grid gap-5 lg:grid-cols-2"><div className="rounded-xl border border-white/10 bg-black/20 p-5"><p className="text-xs font-bold uppercase tracking-wider text-uniblex-blue">Listing</p><h3 className="mt-2 font-heading text-2xl text-white">{draft.title}</h3><p className="mt-3 leading-7 text-uniblex-gray">{draft.shortDescription}</p><p className="mt-4 text-sm text-white">{draft.engine} · {draft.desktop?"Desktop":""}{draft.mobile?" + Mobile":""}</p></div><div className="rounded-xl border border-white/10 bg-black/20 p-5"><p className="text-xs font-bold uppercase tracking-wider text-uniblex-purple">Verification</p><ul className="mt-3 space-y-3 text-sm text-white"><li>✓ Rights and content declarations complete</li><li>{draft.media.find(item=>item.role==="cover")?"✓":"—"} Cover verified</li><li>{draft.media.find(item=>item.role==="thumbnail")?"✓":"—"} Thumbnail verified</li><li>{draft.build?"✓ Build manifest and files verified":"— Build required"}</li></ul>{draft.build?.previewUrl?<Link href={draft.build.previewUrl} target="_blank" rel="noopener noreferrer" className="btn-secondary mt-5 text-sm">Open safe build preview</Link>:null}</div></div></section>;}
function Heading({title,text}:{title:string;text:string}){return <div><h2 className="font-heading text-2xl text-white sm:text-3xl">{title}</h2><p className="mt-2 text-uniblex-gray">{text}</p></div>;}
function Field({label,value,onChange,...props}:{label:string;value:string;onChange:(value:string)=>void}&Omit<React.InputHTMLAttributes<HTMLInputElement>,"value"|"onChange">){return <label className="text-sm font-semibold text-white">{label}<input {...props} value={value} onChange={event=>onChange(event.target.value)} className="mt-2 min-h-12 w-full rounded-xl border border-white/10 bg-black/20 px-4 outline-none focus:border-uniblex-blue"/></label>;}
function Area({label,value,onChange,...props}:{label:string;value:string;onChange:(value:string)=>void}&Omit<React.TextareaHTMLAttributes<HTMLTextAreaElement>,"value"|"onChange">){return <label className="text-sm font-semibold text-white">{label}<textarea {...props} value={value} onChange={event=>onChange(event.target.value)} rows={4} className="mt-2 w-full rounded-xl border border-white/10 bg-black/20 p-4 outline-none focus:border-uniblex-blue"/></label>;}
function CheckBox({checked,onChange,label}:{checked:boolean;onChange:(value:boolean)=>void;label:string}){return <label className="flex min-h-12 items-start gap-3 rounded-xl border border-white/10 bg-black/15 p-3 text-sm text-white"><input type="checkbox" checked={checked} onChange={event=>onChange(event.target.checked)} className="mt-0.5 h-4 w-4 accent-[#00B2FF]"/><span>{label}</span></label>;}
function Progress({label,value}:{label:string;value:number}){return <div className="mt-4"><div className="flex justify-between gap-3 text-xs text-uniblex-gray"><span className="truncate">{label}</span><span>{value}%</span></div><div className="mt-1.5 h-1.5 overflow-hidden rounded-full bg-white/10"><div className="h-full bg-gradient-to-r from-uniblex-blue to-uniblex-purple" style={{width:`${Math.min(100,value)}%`}}/></div></div>;}
function validate(step:number,draft:Draft){const errors:string[]=[];if(step===0){if(draft.title.trim().length<2)errors.push("Add a game title.");if(!draft.categoryId)errors.push("Choose a category.");if(draft.shortDescription.trim().length<20)errors.push("Short description must be at least 20 characters.");if(draft.description.trim().length<40)errors.push("Full description must be at least 40 characters.");if(!draft.ipAccepted||!draft.contentAccepted)errors.push("Complete both rights and content declarations.");}if(step===1){if(!draft.desktop&&!draft.mobile)errors.push("Select at least one supported platform.");if(!draft.controls.trim())errors.push("Add player controls or instructions.");}if(step===2){if(!draft.media.some(item=>item.role==="cover"))errors.push("Upload and verify a cover image.");if(!draft.media.some(item=>item.role==="thumbnail"))errors.push("Upload and verify a card thumbnail.");}if(step>=3&&!draft.build)errors.push("Upload and verify a WebGL ZIP build.");return errors;}
