"use client";
import Link from "next/link";
import { AD_FORMATS, AD_POLICY_VERSION, AUDIENCE_DECLARATIONS, emptyMonetization, HOST_AD_FORMATS, MONETIZATION_MODES, type MonetizationDisclosure } from "@/lib/monetization";
export function MonetizationFields({ value, onChange }: { value: MonetizationDisclosure; onChange: (value: MonetizationDisclosure) => void }) {
  const change = (patch: Partial<MonetizationDisclosure>) => onChange({ ...value, ...patch });
  const list = (text: string) => [...new Set(text.split(/[\n,]/).map(item => item.trim()).filter(Boolean))];
  return <fieldset className="mt-6 rounded-xl border border-white/10 p-5 text-white"><legend className="px-2 font-bold">Monetization / Advertising</legend>
    <label className="block">Does this game contain advertising or monetization?<select className="admin-select mt-2 min-h-12 w-full rounded-xl bg-black/30 p-3" value={value.mode === "none" ? "no" : "yes"} onChange={e => onChange(e.target.value === "no" ? emptyMonetization() : { ...emptyMonetization(), mode: "developer_ads" })}><option value="no">No</option><option value="yes">Yes</option></select></label>
    {value.mode !== "none" && <div className="mt-4 grid gap-4">
      <label>Integration type<select className="admin-select mt-2 min-h-12 w-full rounded-xl bg-black/30 p-3" value={value.mode} onChange={e => change({ mode: e.target.value as MonetizationDisclosure["mode"] })}>{MONETIZATION_MODES.filter(mode => mode !== "none").map(mode => <option key={mode} value={mode}>{({ developer_ads: "Developer-managed ads", uniblex_ads: "Uniblex SDK / host-managed ads", hybrid: "Both integration types" } as Record<string, string>)[mode]}</option>)}</select></label>
      <p className="text-sm text-uniblex-gray">Every provider, placement, tracker, external host, audience declaration, and data use requires review. Host-managed advertising remains disabled until Uniblex configures and approves a real provider. Earnings and payouts are unavailable.</p>
      {(value.mode === "developer_ads" || value.mode === "hybrid") ? <div className="grid gap-4 sm:grid-cols-2">
        <label>Ad provider / monetization service<input className="mt-2 min-h-12 w-full rounded-xl bg-black/30 p-3" value={value.provider} maxLength={160} onChange={e => change({ provider: e.target.value })} /></label>
        <label>Provider integration version<input className="mt-2 min-h-12 w-full rounded-xl bg-black/30 p-3" value={value.providerVersion} maxLength={80} onChange={e => change({ providerVersion: e.target.value })} /></label>
      </div> : null}
      <fieldset><legend>Ad formats</legend><div className="mt-2 flex flex-wrap gap-4">{AD_FORMATS.map(format => <label key={format} className="flex min-h-10 items-center gap-2"><input type="checkbox" checked={value.formats.includes(format)} onChange={e => change({ formats: e.target.checked ? [...value.formats, format] : value.formats.filter(f => f !== format) })} />{format}</label>)}</div></fieldset>
      {(value.mode === "uniblex_ads" || value.mode === "hybrid") ? <fieldset className="rounded-xl border border-white/10 p-4"><legend className="px-2 font-bold">Requested host placements</legend>
        <p className="mb-3 text-sm text-uniblex-gray">These requests stay pending and disabled until the submitted build and each token are reviewed.</p>
        <div className="grid gap-3">{value.placements.map((placement, index) => <div key={`${placement.format}:${placement.token}:${index}`} className="grid gap-2 rounded-lg border border-white/10 p-3 sm:grid-cols-[1fr_160px_2fr_auto]">
          <input aria-label={`Placement ${index + 1} token`} className="min-h-11 rounded-lg bg-black/30 p-3" maxLength={80} placeholder="level_complete" value={placement.token} onChange={e => change({ placements: value.placements.map((item, itemIndex) => itemIndex === index ? { ...item, token: e.target.value } : item) })} />
          <select aria-label={`Placement ${index + 1} format`} className="admin-select min-h-11 rounded-lg bg-black/30 p-3" value={placement.format} onChange={e => change({ placements: value.placements.map((item, itemIndex) => itemIndex === index ? { ...item, format: e.target.value as typeof placement.format } : item) })}>{HOST_AD_FORMATS.map(format => <option key={format}>{format}</option>)}</select>
          <input aria-label={`Placement ${index + 1} trigger`} className="min-h-11 rounded-lg bg-black/30 p-3" maxLength={240} placeholder="After the player completes a level" value={placement.trigger} onChange={e => change({ placements: value.placements.map((item, itemIndex) => itemIndex === index ? { ...item, trigger: e.target.value } : item) })} />
          <button type="button" className="btn-secondary min-h-11" onClick={() => change({ placements: value.placements.filter((_, itemIndex) => itemIndex !== index) })}>Remove</button>
        </div>)}</div>
        <button type="button" className="btn-secondary mt-3" disabled={value.placements.length >= 24} onClick={() => change({ placements: [...value.placements, { token: "", format: "interstitial", trigger: "" }] })}>Add placement</button>
      </fieldset> : null}
      <label>Tracker / measurement disclosures (one per line)<textarea className="mt-2 w-full rounded-xl bg-black/30 p-3" rows={3} value={value.trackers.join("\n")} onChange={e => change({ trackers: list(e.target.value) })} placeholder="Provider or tracking purpose" /></label>
      <label>External network hosts (exact HTTPS origins, one per line)<textarea className="mt-2 w-full rounded-xl bg-black/30 p-3" rows={3} value={value.externalHosts.join("\n")} onChange={e => change({ externalHosts: list(e.target.value) })} placeholder="https://ads.example.com" /></label>
      <label>Audience / age declaration<select className="admin-select mt-2 min-h-12 w-full rounded-xl bg-black/30 p-3" value={value.audience} onChange={e => change({ audience: e.target.value as MonetizationDisclosure["audience"] })}>{AUDIENCE_DECLARATIONS.map(audience => <option key={audience} value={audience}>{({ not_declared: "Select a declaration", general_13_plus: "General audience, 13+", mixed_or_unknown: "Mixed or unknown audience", directed_to_children: "Directed to children" } as Record<string, string>)[audience]}</option>)}</select></label>
      <label>Data-use disclosure<textarea className="mt-2 w-full rounded-xl bg-black/30 p-3" rows={3} maxLength={1200} value={value.dataUse} onChange={e => change({ dataUse: e.target.value })} placeholder="Describe data collected, purposes, retention, and sharing." /></label>
      <label className="flex gap-2"><input type="checkbox" checked={value.externalDestinations} onChange={e => change({ externalDestinations: e.target.checked })} />Ads open external destinations</label>
      <label>Integration details and review instructions<textarea className="mt-2 w-full rounded-xl bg-black/30 p-3" rows={4} maxLength={2000} value={value.notes} onChange={e => change({ notes: e.target.value })} /></label>
      <Link className="text-uniblex-blue underline" href="/game-monetization-policy" target="_blank">Read the advertising policy</Link>
      <label className="flex gap-2"><input type="checkbox" checked={value.policyVersion === AD_POLICY_VERSION} onChange={e => change({ policyVersion: e.target.checked ? AD_POLICY_VERSION : null })} />I confirm that this game's advertising complies with the Uniblex Game Monetization &amp; Advertising Policy.</label>
    </div>}
  </fieldset>;
}
