import Link from "next/link";
import { AD_POLICY_VERSION } from "@/lib/monetization";
export const metadata = { title: "Game Monetization & Advertising Policy | Uniblex" };
export default function AdvertisingPolicy() {
  return <main className="mx-auto max-w-4xl px-5 py-16 text-white"><h1 className="font-heading text-3xl sm:text-5xl">Uniblex Game Monetization &amp; Advertising Policy</h1><p className="mt-4 text-uniblex-gray">Version {AD_POLICY_VERSION}</p>
    <section className="mt-8 space-y-5 leading-8"><h2 className="font-heading text-2xl">Can I upload a game containing ads?</h2><p>Yes. Monetized games may be submitted subject to advertising, security, player experience, and review requirements. Disclose every provider, format, external destination, tracking purpose, and integration before review. Uploading a build does not approve its advertising.</p>
    <h2 className="font-heading text-2xl">Integration and review</h2><p>Developer-managed advertising runs in your game and requires individual review. Approval does not endorse a third-party provider. Uniblex SDK / host-managed advertising is the preferred integration: the host decides availability and controls provider rendering. Host advertising is unavailable until a production provider is configured. Hybrid integrations must disclose both.</p>
    <h2 className="font-heading text-2xl">Prohibited behavior</h2><ul className="list-disc space-y-3 pl-6"><li>Malware, malicious scripts, phishing, credential theft, crypto mining, browser hijacking, or illegal content and services.</li><li>Deceptive advertising, fake download buttons, forced downloads, ads disguised as game controls, or inappropriate content.</li><li>Unauthorized redirects, auto-redirect advertising, uncontrolled popups or popunders, excessive new tabs, and ads that prevent normal play or leaving the game.</li><li>Abusive tracking or collection and transmission of sensitive information without authorization.</li><li>Attempts to escape iframe restrictions, interfere with Uniblex UI, or bypass security and review controls.</li></ul>
    <h2 className="font-heading text-2xl">Player experience</h2><p>Ads must not make a game unusable. Rewarded ads must be initiated by the player, with a clear reward choice. Interrupt gameplay only at sensible boundaries. Games must resume after failed, unavailable, skipped, or blocked ads. Grant a reward only after a successful host/provider completion result.</p>
    <h2 className="font-heading text-2xl">Security and privacy</h2><p>Games run as untrusted content. Advertising approval does not grant popup, top-navigation, download, or iframe-escape permissions. Do not send passwords, access tokens, private profiles, advertising identifiers, or unnecessary personal information through the SDK. Declare external network dependencies and obtain any required authorization and consent.</p>
    <h2 className="font-heading text-2xl">Enforcement and changes</h2><p>Uniblex may request changes, reject submissions, or remove games that violate this policy. Policy changes, providers, new builds, and monetization changes may require re-review. Automated scans are limited indicators and do not certify a build as safe.</p>
    <h2 className="font-heading text-2xl">Revenue reporting</h2><p>Revenue sharing, payouts, and earnings reporting are not yet available. This policy makes no revenue, fill-rate, or payment commitment. Future accounting must use verified provider or server records.</p>
    <Link className="text-uniblex-blue underline" href="/developers/sdk">Browser SDK documentation</Link></section></main>;
}
